sudo: required
cache:
    - bundler
    - apt
language: ruby
branches:
    only:
        - master

env:
    # default naming-patter: branch-commitid.PDF
    - outputfilename="${TRAVIS_BRANCH}-${TRAVIS_COMMIT}"

before_install:
    # add latest latex packages to apt-get repos
    - sudo add-apt-repository ppa:texlive-backports/ppa -y

install:
    # update apt-get to get newest versions
    - sudo apt-get update
    # get basic LaTeX stuff
    - sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-pictures
    # get LaTeX 3
    - sudo apt-get install texlive-latex3
    # get basic biblatex stuff
    - sudo apt-get install texlive-bibtex-extra biblatex 
    # get chktex to check our LaTeX
    - sudo apt-get install chktex
 
script:
    # if we have a TAG provided, use this as filename: tag.PDF
    - "echo ${#TRAVIS_TAG}; if [ ${#TRAVIS_TAG} -gt 0 ]; then outputfilename=${TRAVIS_TAG}; fi"

    - chktex -W # Print version information.
    - chktex *.text 2>/dev/null | tee lint.out

    # If chktex returned an error, then break
    - test ! -s lint.out

    # now actually build the PDF
    - pdflatex main.tex

after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --quiet --branch=travis-build https://${GH_TOKEN}@github.com/mcnultyyy/cv travis-build
    - cd travis-build
    - cp -f ../main.pdf .
    - git add main.pdf
    - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
    - git push -fq origin travis-build