sudo: required
dist: trusty
language: generic

cache:
  - apt
branches:
  only:
    - master

before_install:
  - docker build --tag texlive .
  - docker run -t --rm --volume "$(pwd):/tmp:rw" texlive pdflatex main

after_success:
  - git config --global user.email ${GIT_EMAIL}
  - git config --global user.name ${GIT_NAME}
  - git clone --quiet --branch=travis-build https://${GH_TOKEN}@github.com/mcnultyyy/cv travis-build
  - cd travis-build
  - cp -f ../main.pdf .
  - git add main.pdf
  - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
  - git push -fq origin travis-build